version: '3'
services:
  vue-client:
    build: ./client
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "8080:8080"

  node-server:
    build: ./server
    command: bash -c "npm install && npm run serve"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "9000:9000"
  mongo:
    image: library/mongo:4.4-bionic
    container_name: 'db-exam-wtat1-sose21-pz1'
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 27017-27019:27017-27019
