version: '3'
services:
  mongo:
    image: library/mongo:4.4-bionic
    container_name: 'db-exam-wtat1-sose21-pz1'
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 27017-27019:27017-27019
